### ISSUE TITLE
Error with my number password

### ISSUE THREAD

**Issue by Axel3026** [LeagueOfPoro/EsportsCapsuleFarmer#47]
![Screenshot_1](https://user-images.githubusercontent.com/87623383/187275195-da114bf4-5f1f-41dd-9b13-28ab1ab6e8f8.png)

If I have my password with only numbers it does not detect it

**Comment by Axel3026** [comment]
I do not understand anything about how this works but it is putting a 0 at the end of my password
![Screenshot_2](https://user-images.githubusercontent.com/87623383/187277283-d7230b74-ec42-40d1-9ec6-09331635e60e.png)
![Screenshot_3](https://user-images.githubusercontent.com/87623383/187277287-752e5877-e0c7-469d-bcd2-6c07b45078e2.png)

**Comment by MrBartusek** [comment]
It's yaml thing, use quotation marks here

```yaml
headless: false
autologin:
  enable: true
  username: "YourUsername"
  password: "3928392."
  ```
